# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automagically:
    name: "Executing E2E tests 🚀"
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: OctoMind-dev/automagically-action-execute@v2
        with:
          url: https://app.clickup.com/
          token: ${{ secrets.AUTOMAGICALLY_TOKEN }}
          testTargetId: 43cbfaa9-66bd-4ad6-8870-f77f44a8ef8c
          blocking: false
